language: php

php:

  - '5.6'

before_install:

  - mv .env.example .env

#  - php /home/travis/.phpenv/versions/5.3.26/bin/composer.phar self-update

install:  

  - composer install

script:

  - php artisan key:generate

  - vendor/bin/phpunit
