language: php
php:
  - '5.6'
before_script:
  - git clone https://github.com/austintoddj/Canvas.git canvas
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script: phpunit --configuration phpunit.xml --coverage-text
