language: php

php:
  - '5.6'

before_script:
  - php /home/travis/.phpenv/versions/5.3.26/bin/composer.phar self-update
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
